FROM php:8.3-apache

# Dependências do sistema (incluindo ICU para intl)
RUN apt-get update \
  && apt-get install -y \
     zlib1g-dev \
     libzip-dev \
     libjpeg-dev \
     libpng-dev \
     libicu-dev \
     wget \
     gnupg \
  && docker-php-ext-install opcache

# Extensões PHP
RUN docker-php-ext-configure zip \
  && docker-php-ext-configure gd --with-jpeg \
  && docker-php-ext-install zip gd intl

# PDO
RUN docker-php-ext-install pdo pdo_mysql

# Apache config
COPY .docker/apache/vhost.conf /etc/apache2/sites-available/000-default.conf

# Certificado
COPY .docker/php/cacert.pem /usr/local/etc/php/cacert.pem

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin \
    --filename=composer

# Apache rewrite
RUN a2enmod rewrite

WORKDIR /var/www/html
